// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukyqaokknwfgrvibrvxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVreXFhb2trbndmZ3J2aWJydnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTY5MTEsImV4cCI6MjA2MzgzMjkxMX0.te0AiDwFWDXYr9UU-2saRiva1vBQvu1wdDFYmMkFsqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);